# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-13 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='productos',
            new_name='recetas',
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(upload_to='recetas'),
        ),
    ]
