# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Correo',
            new_name='Suscriptores',
        ),
    ]
