# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-10 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
